=head1 RTIR Administrative Tutorial

=head2 Blocks Queue

Discussed a little in Tutorial

=head2 Custom Fields

default values in Config
We discuss IP in Tutorial

=head2 Scrips

RTIR specific scripts

=head2 Templates

=over 4

=item Autoreply in Blocks queue

This template is sent when a block is created.

=item BlockRemoved in Blocks queue

This template is sent when a block is removed.

=item Autoreply in Investigations queue

This template is sent when a new investigation is launched.

=back

=head2 GnuPG Encryption

Documented in RT L<RT::Crypt::GnuPG>
GnuPG integration is now a feature of RT.  Configuration
can be done in your RT_SiteConfig.pm file and you can
find extensive documentation by reading. 

=head2 Locking

See the documentation for L<RT::Extension::TicketLocking>

=head2 Aging

See the documentation for L<RT::Extension::TicketAging>

=head2 Maintaining DB size, deleting entries, restoring deleted data

During normal operation RT/RTIR never deletes data from the database.
Since RT 3.7 the RTx::Shredder extension has been integrated into
RT.  This extension can remove data such as Users or Tickets
from the RT/RTIR system. You can find documentation for this 
extension in in L<RT::Shredder>  by running `perldoc lib/RT/Shredder.pm`
RT::Shredder's documentation includes information on restoring deleted data
from backups. RT::Shredder provides SQL commands to reverse any delete
operations, so any data that it deletes may be restored.

