=head1 REQUIREMENTS for Multiple Constituency functionality

SWITCHCERT, and several other CSIRT's provide services for more
than one constituency.  For a variety of reasons, it makes sense
to separate these constituencies, particularly when handling
incidents. However, it also makes sense to use the same tools when
working on these separate sources of data. Depending on the
constituency different users may wish to work on incidents within
different queues or have access to incident data held within different
queues. Therefore, access is required, which allows user privileges
depending on the constituency. RTIR does not support this out of
the box. Of course it would be possible to install one separate
instance of RTIR per constituency. But this is somewhat cumbersome,
as a lot of the configuration is identical on all instances, hence
error-prone.  A better solution would be to integrate the facility
of handling several constituencies within the same instances of
RTIR.

 D.3.5.1. We MUST be able to define more than one constituency.
 D.3.5.2. We MUST be able to define Access Control Lists according to the constituency.
 D.3.5.3. We MUST preset the constituency according to mail traffic.
 D.3.5.4. RTIR MUST allow constituency inheritance of newly created tickets in any RTIR
  queue (incident report, incident, blocks, investigation)

=head2 Definitions 

  A constituency is defined by:
  * It's name.
  * Its correspondence email address.
  * Associated ACLs.
  * Assigning a constituency to a ticket:
  ** On new incoming incident report, the constituency is preset
     automatically according the email address the email is sent to.
  ** Any new incidents created from incident reports, or blocks and
     investigations, created from incidents inherit the constituency
     from the launching ticket.
  ** Manually assign the constituency to any new tickets created from
     within RTIR, not yet related to any other ticket.
  ** Manually change the constituency of a ticket and all its related
     tickets.

Of course the last two points require that the user has the right to do so,
according to the ACLs. All tickets must belong to a constituency.

=head1 IMPLEMENTATION DETAILS

=head2 Mandatory

The constituency field is a mandatory field, so users must select value for
the field during creation of tickets in RTIR's queues.

=head2 Constituency values

Constituency is a custom field that applies to all RTIR's queues. Administrator
can manage the field and its values via the web interface: RT -> Configuration ->
Custom Fields -> click on '_RTIR_Constituency' record in the list. At the bottom
of the page there is control elements to add, delete and rename values of
the constituency field.

However, to get advanced control over constituencies you have to create additional
objects in the system. We'll describe steps below, but as well admins may use the
F<add_constituency> script in the etc directory which helps add and new constituency
values, along with their associated groups and queues.

=head2 Managing constituency values

In some simple configurations,administrators may use the web interface
to add/delete or rename values to the 'Constituency' field, however
if you need the advanced access control RTIR's Constituencies system
provides, you need to create several queues and groups for each
value. To simplify this task you can used the F<add_constituency>
script. You can find it in the etc directory of RTIR's distribution.
This script adds new values to the field and creates several objects
in the system if those don't exist. It also grants basic constituency
rights.

For example the following objects affect the rights users can have to the constituency 'EDUNET':

=over 4

=item * Queue 'Incident Reports - EDUNET'
=item * Queue 'Incidents - EDUNET'
=item * Queue 'Inestigations - EDUNET'
=item * Queue 'Blocks - EDUNET'
=item * Group 'DutyTeam EDUNET'

=back

These queues are used as sources of LIMITED information for
per-constituency information for tickets in the master queue.  You
can set constituency base correspond and comment addresses. You'll
find more details about that later.

Read more about granting rights using special queues and groups below in 
the ACL section.

=head2 Value propagation algorithms

An administrator can use the C<$_RTIR_Constituency_Propagation> config option to
choose RTIR's behaviour on constituency inheritance between linked tickets.
There are three algorithms at the moment: 'no', 'inherit' and 'reject'.
These algorithms are defined in L</Changing the value>

=head3 Introduction

Before we start discussing algorithms in depth let's look at the primary ways of
setting and changing value of the 'Constituency' field:

=over 4

=item Creating a new ticket without links.

The simplest case. User creates a new ticket and there is no reference to
another ticket which already exists in the system. For example user creates
an IR using the Web UI by clicking RTIR -> Incident Reports -> New Report,
fills in values, leaves the Incident input blank. In this case default value
from the config is used, however user can change constituency.

A similar situation happens when ticket is created using the email interface.
Find out more about that in the 'Presetting constituency according to mail
traffic' section below.

=item Creating a new ticket with a link.

RTIR allows users to create new tickets and link them with another
as a single step. For example a user can create a new IR from an Incident
or launch an Investigation from it. When user is looking at a creation
page we already know all information about the ticket he's creating a new
one from, so we select default constituency value based on the ticket the user
is going to link to. This is one of situations where the option plays
its role. Depending on the configuration, we can allow user to change 
constituency of the new ticket or not.

There is another scenario you should be aware of: when user is creating
a ticket he can enter the ID of an Incident into an input field. In this case
we don't know anything about the incident beforehand and operation may
be interrupted later on - at the form submit.

=item Changing the value

Changing constituency of a ticket can affect linked tickets as well.

=back

The three propagation algorithms:

=head3 no

This is the default algorithm. Any combinations are allowed. Users can link
tickets with different constituencies, changing the value of a ticket doesn't
affect linked tickets. However, reasonable defaults are suggested. For example
when a user creates a new ticket from another one we select constituency of the
latter ticket by default instead of using the default value from the config.

=head3 reject

This algorithm doesn't allow user to link tickets with different values of
the 'constituency' field.

Users can not change the 'constituency' field's value when create a new ticket from another one.

During linking tickets together, the list of possible candidates is restricted by
constituency of the former ticket, so user may not choose targets with different
constituencies.

Changing constituency value through the 'Edit' page is possible ONLY if
the ticket is not linked to any other tickets.

=head3 inherit

This algorithm is something in between of the above two. Operations are not
rejected, instead we prefer the value of a new incident when user links tickets
together.

If the user uses 'New' or 'Launch' links on the main view of an incident,
investigation, incident report or block to create new linked ticket then
the creation page contains a predefined value for constituency and can't be
changed at this point.

Changing constituency value is possible through the 'Edit' page. RTIR
updates all related tickets during this action, so all continue to have
the same value.

Note that while linking tickets together, the list of possible candidates
is not restricted by the constituency of the initial ticket, so a user may
choose targets with different constituencies. In the latter case the incident's
constituency value is always preferred.

=head2 Outgoing mail: "CorrespondAddress" and "CommentAddress"

If you create queues as described in the L</Managing constituency values>
section, their correspondence and comment addresses will override
the original queue's where possible.

For example an user replies to an IR with constituency EDUNET and RTIR
sends notifications then correspond address of 'Incident Reports - EDUNET'
queue is used in notifications, but only if it's not empty. If the field
is empty then correspond address of 'Incident Reports' queue is used
unless it's empty too. The last resort is $CorrespondAddress in the RT's
config file.

It is important to note that these additional rights do NOT also
add new mailing rules.  

=head2 Presetting constituency according to mail traffic

Many mail transfer agents (MTAs) allow you to specify a flag on any incoming
email message by appending "+flag" after an email address. (This option
is supported by postfix, sendmail, qmail, exim and others, though the "+" delimiter
has different defaults on some systems and can be customized by a site's systems
administrator)

RTIR's multiple constituency support uses this extension mechanism to allow
a single queue to receive mail for multiple constituencies. If you have two
constituencies, EDUNET and GOVNET, you might set up RTIR's "incident report"
address as follows in /etc/aliases:

    edu: abuse+edunet
    gov: abuse+govnet
    abuse: "|/path/to/rt-mailgate ...mailgate options..."

The rt-mailgate script expect that MTA sets the EXTENSION environment variable
with value of "flag". The script adds this value to the incoming message in
the 'X-RT-Mail-Extension' header's field. If an incoming mail has
'X-RT-Mail-Extension: <valid constituency value>' header field then new
ticket is created and constituency set according to field value.

The constituency field is mandatory so if the mail gate is not configured
then the default value from the config is used.

=head2 ACLs

RTIR allows you to grant additional rights to tickets based on their
constituency by means of "pseudo" queues ("Incidents - EDUNET" for
the EDUNET constituency on the Incidents queue, for example.)

For example, assume you have two constituencies "EDUNET" and "GOVNET".
Your RTIR instance consists of four queues: Incident Reports,
Incidents, Investigations and Blocks.  To grant the user "Edward"
the right to work with EDUNET Incident Reports, you'll need to
create a new queue, "Incident Reports - EDUNET".  Make "Edward" an
AdminCc of the new queue, either directly or as a member of a group
like "DutyTeam EDUNET".

You should grant that user or group the rights you want them to
have to tickets in the "Incident Reports" queue. It is important
that you NOT grant the user or group "queue-wide" rights such as
"See Queue" or "Create Ticket" in the pseudo-queue as the system
will apply those rights to the pseudo-queue "Incident Reports -
EUDNET" and NOT to the "Incident Reports" queue.

=head3 Constituency specific groups

For each constituency value admin can create a group
'DutyTeam constituency_value' using either the web UI or the script.

We've added a little bit automation for such groups. Those groups
are added as AdminCc to a ticket according to value of the field.
And you can grant additional rights using this fact. For example
if you grant 'TakeTicket' right to AdminCc role of IR queue
then users that are members of 'DutyTeam EDUNET' group will have
this rights on all EDUNET tickets.

Note that this method has some limitations and caveats .Users who
has enough privileges still can add other users and groups as
AdminCcs of a ticket and these principals will get the same set of
additional rights constituency specific group get via AdminCc role.
As you use AdminCc role only then you can not use it to grant one
set of rights to group X and another set to group Y.

=head3 DutyTeam group vs. constituency specific group

By default DutyTeam has almost all rights on all RTIR's queues, rights
this group has applies to tickets with all constituencies, so if you
want to give access to group 'DutyTeam EDUNET' on EDUNET tickets only
then it's not good idea make this group member of DutyTeam.

In RT/RTIR you can not deny right for a subgroup of a group if the latter
has it, so you should avoid adding groups into groups with higher
privileges. We suggest leave DutyTeam and constituency specific group
on the same level, however, you can join them using a new top level
group.

The same rules applies to user members of groups. Rights of all groups
a user is member of are summed up and if he is member of DutyTeam with
default of rights then he has more rights than any member of
constituency specific group (who is not member of other groups).
Considering above suggestion a good way to deal with users is to place
each user into constituency specific groups user should have access to
and place her into DutyTeam only if he should work with all constituencies.

