=head1 RTIR Documentation Index

RTIR's documentation can be found in POD form in the docs/
subdirectory of your RTIR install.  Some things may be documented
with specific tools (such as rt-mailgate) or with RT's standard 
documentation.  Other topics will be documented in
the perl modules that comprise RTIR

=head2 Email

=head3 Create new IR via e-mail

Mailgate help: rt/bin/rt-mailgate --help

=head3 Reply from requestor on IR via e-mail

Mailgate help: rt/bin/rt-mailgate --help

=head3 Encrypting Mail with GnuPG

See L<RT::Crypt::GnuPg> and L<AdministrationTutorial/GnuPG Encryption>

=head2 Creating 

These Actions work in the same manner as creating tickets in RT

=over 4

=item Create new IR via web-interface

=item Create new Incident via web-interface

=back

=head3 Create new block via web-interface

L<Tutorial/'Creating a Block'>

=head2 Managing Incident Responses

=head3 Merge IR

L<Tutorial/Merging Tickets>

=head3 Split IR

L<Tutorial/'Splitting tickets'>

=head3 Reject IR

L<Tutorial/'Rejecting an IR'>

=head3 Bulk Reject IR

L<Tutorial/'Rejecting many IRs at once (bulk reject)'>

=head3 Linking IRs to Incidents

=over 4

=item Link IR with new Incident

=item Create new Incident from IR via 'Basics' section

=item Link IR with existing Incident

=back

L<Tutorial/'Linking IRs to Incidents'>

=head2 Reply Reporters Incident

L<Tutorial/'Reply to Reporters'>

=head2 Reply All Incident

L<Tutorial/'Reply to All'>

=head2 Link Incident with new IR

L<Tutorial/'Linking Incidents to IRs, Investigations, etc.'>

=head2 Link Incident with existing IR

L<Tutorial/'Linking Incidents to IRs, Investigations, etc.'>

=head2 Link Incident with new Block

L<Tutorial/'Linking Incidents to IRs, Investigations, etc.'>

=head2 Link Incident with existing Block

L<Tutorial/'Linking Incidents to IRs, Investigations, etc.'>

=head2 Resolve Incident

L<Tutorial/Resolving an Incident>

=head2 Resolve Incident & linked IR's and Investigations

L<Tutorial/Resolving an Incident>

=head2 Quick resolve Incident

L<Tutorial/'Quick Resolve'>

=head2 Reopen Incident

=head2 Abandon Incident

L<Tutorial/'Abandoning Incidents'>

=head3 Bulk Abandon Incidents

L<Tutorial/'Abandoning Incidents', subsection 'Abandoning many Incidents at once (bulk abandon)'>

=head2 Launch Investigation

L<Tutorial/'Linking Incidents to IRs, Investigations, etc.'>

=head2 Reply from correspondent on Blocks via e-mail

=head2 Correspond with Correspondent

L<Tutorial/'Correspond with Correspondent'>

=head2 Comment Blocks via web-interface

=head2 Merge Blocks

=head2 Split Blocks

=head2 Remove Blocks

=head2 Activate Blocks

=head2 Steal Blocks

=head2 Reply IR via web-interface

=head2 Comment IR via web-interface

=head2 Reply from correspondent on Investigation via e-mail

=head2 Comment on Investigation via web-interface

=head2 Resolve IR

=head2 Reopen IR

=head2 Update Incident via e-mail

=head2 Comment Incident via web-interface

=head2 Merge Investigation

=head2 Split Investigation

=head2 Resolve Investigation

=head2 Reopen Investigation

=head2 Steal Investigation

=head2 Merge Incident

=head2 Split Incident


