=head1 RTIR Administrative Tutorial

=head2 General Configuration

RT and RTIR store many configuration items in configuration files
on the file system in the etc directory in your RT directory.
F<RT_Config.pm> and F<RTIR_Config.pm> provide documentation on all available
configuration options and also set system defaults. You can view these
files to see what configuration options are available, but don't edit
these files to change configuration values. The F<RT_SiteConfig.pm> file
is specifically provided to store your core site-specific configurations
and you may create F<RTIR_SiteConfig.pm> for customizations to configuration
declared in F<RTIR_Config.pm>.  F<RTIR_SiteConfig.pm> is normally
created in /opt/rt4/etc/.

To change a configuration value, copy the Set code from F<RT_Config.pm>
or F<RTIR_Config.pm> and add it to the relevant Site Config. Then set
your custom configuration values there.

=head2 Countermeasures Queue

You may disable the Countermeasures queue by putting the following into your
F<RTIR_SiteConfig.pm> config:

    Set($RTIR_DisableCountermeasures, 1);

You will probably also want to disable the Queue using the RT
Administrative interface.  Tools -> Configuration -> Queues -> Countermeasures,
uncheck Enabled and click Save Changes.

=head2 Status

The various states an incident, IR, investigation, or countermeasure can be in,
such as 'open', 'stalled', 'abandoned', etc.

This field contains custom statuses for tickets, and values are different in
different queues. The status values are set via the C<%Lifecycles> option in
the RTIR configuration file. You can read more about Lifecycles in the
F<RT_Config.pm> file.

Status is a critical field for functionality.

For more information, read the description in F<RTIR_Config.pm> and description
of L</Scrips> below.

=head2 Custom Fields

When RTIR is installed several custom fields are created and applied
to queues in RTIR. Some of these custom fields are important for
RTIR functionality and can not be renamed, disabled or un-applied,
but other fields can be.

=over 4

=item Constituency

The constituency of an incident, IR, investigation, or countermeasure.

Additional quite heavy automation is tied to this field. This
is described in L<Constituencies> doc. Don't rename this field
if you want to use this functionality.

=item Description

Short description of an Incident.

=item Resolution

How an Incident was or wasn't resolved.

=item Function

Who is handling the Incident.

=item Classification

The type of Incident, such as system compromise or denial of service.

=item How Reported

How the IR got into RTIR.

=item ReporterType

Context for the incident reporter, such as the police, other ISP,
or external individual.

=item IP

IP addresses related to the incident, IR, investigation, or countermeasure.

Don't rename this custom field or it will lose all associated features.
It's possible to change this CF from multiple values to single value.

See L<Tutorial/IP> for more information.

See also L</SetIPFromContent> below.

=item Netmask

Network mask for a block countermeasure.

=item Port

Port for a network block.

=item Where Blocked

Where the network block is placed.

=item Customer

Customer for an IR or Investigation.

=back

=head2 Managing "RT at a glance" and "RTIR at a glance" pages

In the config you can set the @RTIR_HomepageComponents option to control
allowed portlets people can add to thier workspace. RT has its own
option $HomepageComponents so you can list different sets for RT and
RTIR. See L<Tutorial> for more information.

=head2 Notifications

Almost all email notifications in RT/RTIR are controlled via scrips.

There are three default base actions you can use to notify users:

=over 4

=item Notify

Sends a notification to users. The reply-to field is set
based on the correspond address. The NotifyActor option also
influences the set of recipients.

=item Notify As Comment

Similar to 'Notify', but the reply-to field is set based on
the comment address.

=item Autoreply

A variation of the 'Notify' action which sends email even if the
NotifyActor option is disabled.

=back

The above actions have multiple variants with different list of recipients,
for example 'Notify Owner' or 'Notify Requestors'. The list of recipients
may contain the following values: 'Requestors', 'Owner', 'Ccs', 'AdminCcs'
and 'Other Recipients'. 'Other Recipients' is the only special case,
these are users who are listed as one-time recipients on the ticket's
reply/comment pages. All other entries are watchers of a ticket.
The list can be a combination of values like 'Owner, Ccs, AdminCcs'.

Here are several examples:

    On Correspond Notify Requestors and Ccs with template Correspondence
    On Create Autoreply To Requestors with template Autoreply
    On Owner Change Notify Owner with template Transaction

Text of notifications is controlled using templates where a queue's template
can override the global one. For example you can create a template 'Correspondence'
in a queue and all notifications (global or queue specific) will use
that template instead of the global template.

=head2 Scrips

Scrips run for every transaction on a ticket in RT and RTIR,
sometimes changing values based on the transaction being
performed. Transactions are any change to a ticket, whether
updating a status or replying to a requestor.

=over 4

=item SetHowReported

Applies to the Incident Reports queue.
On ticket creation, sets the HowReported custom field to a default
value of Email if it isn't otherwise specified.

=item On Correspond Change Status of the Countermeasure

On replies, changes the status of countermeasures according to a few rules
that are described in L<RT::Action::RTIR_SetCountermeasureStatus/DESCRIPTION>.

RT's default L<RT::Action::AutoOpen> is disabled for countermeasures to
avoid unwanted changes of status from 'pending activation'
to 'active'.

See also the C<$RTIR_BlockAproveActionRegexp> option
in the config.

=item On Linking To Incident Activate Report

=item On Correspond (not every) Activate Report

IRs are activated (status changed to first possible active status,
by default 'open') only when they are linked to an incident.
These two scrips take care of that.

RT's default L<RT::Action::AutoOpen> is disabled for IRs to avoid
unwanted changes of status when an IR is not linked. When an IR is
linked to an Incident, L<RT::Condition::RTIR_RequireReportActivation>
checks everything that RT's AutoOpen checks and the scrip behaves in
the same way.

=item Set Due Date On Incident

Keeps the Due date of incidents in sync with the most due child.

See L</"Service Level Agreements (SLAs)"> below for details on automating
Due dates, and L<RT::Action::RTIR_SetDueIncident> for details
about action of the scrip.

It is now possible to edit the Due date of Incidents manually, however
editing a child's Due Date will disable this (and Incident Due dates are
not copied down to Children).

=item ResolveAllChildren

Applies to the Incidents queue.

If an incident is changed to an inactive status, looks for linked tickets in
the Incident Reports, Investigations or Countermeasures queues and resolves
them.  If any of these linked tickets are linked to other ongoing incidents, a
comment is added and they remain unresolved.

=item FixOwnership

Applies to the Incidents queue.

When the Owner of an incident is changed, the Owner of linked children
tickets are changed to the same owner.

Applies to the Incident Reports, Countermeasures and Investigations queues.

When the Owner of a ticket in these queues is changed, that change
is also applied to the linked incident.

=item ReopenIncident

Applies to the Incident Reports, Countermeasures and Investigations queues.

If the status of a ticket in these queues is changed from rejected or
resolved, the linked parent incident ticket status is set to open.

=item SetDefaultIncidentResolution

Applies to the Incidents queue.

When an incident's status is changed, if it is changed from an
inactive status to an active status, the Resolution custom field
is cleared. If it is changed from an active status to an inactive status
and the Resolution custom field isn't set manually, it is set
to the value set in %RTIR_CustomFieldsDefaults in your
F<RTIR_Config.pm>.

=item NotifyOnClose

Applies to the Countermeasures queue.

When a countermeasure ticket is moved from an active status to an inactive
status (closed), the requestors on the countermeasure are notified using the
L<Templates/BlockRemoved in Countermeasure queue> template.

=item SetIPFromContent

Applies to the Incident Reports, Countermeasures, Incidents and Investigations
queues.

Updates the ticket custom field IP to have a list of all IPs and IP ranges
found in the body of the ticket during Create and Correspond.

If configuration of the CF allows only one value then only first IP
from the content is used.

It's OK to disable this scrip.

=item SetConstituency

Applies to the Incident Reports, Countermeasures, Incidents and Investigations queues.

Uses the Constituency algorithms discussed in F<docs/Constituencies.pod> to
set and propagate changes to the Constituency custom field.  On ticket
creation, Constituency is set based on the parent ticket, the
X-RT-Mail-Extension header (see F<docs/Constituencies.pod>) or the default set
in your F<RTIR_Config.pm>

When linking tickets or changing the Constituency custom field, this
scrip ensures that the change is propagated based on your choice of
_RTIR_Constituency_Propagation in your F<RTIR_Config.pm>

=item SetConstituencyGroup

Applies to the Incident Reports, Countermeasures, Incidents and Investigations queues.

When tickets are created, or the Constituency custom field is updated,
this scrip manages the assignment of DutyTeam groups as AdminCcs.
It makes sure that for a Constituency EDUNET, a DutyTeam group
named 'DutyTeam EDUNET' is assigned as AdminCc and removes other DutyTeam
groups from the AdminCc.  L<Constituencies/ACLs> discusses
how to use these groups.

=back

=head2 Templates

=over 4

=item Autoreply in Countermeasures queue

This template is sent when a countermeasure is created.

=item BlockRemoved in Countermeasure queue

This template is sent when a countermeasure is removed.

=item Autoreply in Investigations queue

This template is sent when a new investigation is launched.

=back

=head2 Locking

See the documentation for L<RT::Extension::TicketLocking>

=head2 Aging

See the documentation for L<RT::Extension::TicketAging>

=head2 Maintaining DB size, deleting entries, restoring deleted data

During normal operation RT/RTIR never deletes data from the database.
Since RT 3.7 the RTx::Shredder extension has been integrated into
RT.  This extension can remove data such as users or tickets
from the RT/RTIR system. You can find documentation for this
extension in L<RT::Shredder> by running `perldoc lib/RT/Shredder.pm`
or on the Best Practical website at
L<http://bestpractical.com/rt/docs/latest/RT/Shredder.html>.
RT::Shredder's documentation includes information on restoring deleted data
from backups. RT::Shredder provides SQL commands to reverse any delete
operations, so any data that it deletes may be restored.

=head2 GnuPG and S/MIME support

GnuPG and S/MIME integration is a core feature of RT.  Configuration
can be done in your F<RT_SiteConfig.pm>.
See also the documentation in L<RT::Crypt>.

=head3 Reverification

RTIR supports reverification of incoming email. If a user sends signed mail
but RTIR doesn't have his public key (or if some other error occurs), then his
message will be be processed, but there will be "This message is
unverified" warnings in the UI. Afterwards, RTIR will automatically attempt to
reverify that message whenever someone views it.

=head3 Key selection

Sometimes a user will have multiple public keys in RTIR's GPG database. When
that happens, RTIR has the user writing the message decide which key to use
when sending that user encrypted mail. They are listed as fingerprints along
with their trust levels. If only one key is valid, then RTIR will
automatically choose it instead of asking the user.

If a user has no trusted keys, then the web interface will warn and refuse to
send him an encrypted message. This is ultimately due to limitations in GnuPG:
we cannot encrypt a message with an untrusted key.  Managing the trust levels
of keys must be done outside of RT as there is not currently key management
support available.

=head3 Missing passphrase

If RTIR is asked to sign an outgoing message and the passphrase is unavailable,
it will detect this and avoid sending any email. The user will be asked to
notify a system administrator.

A missing passphrase occurs when GPG Agent is unresponsive or the passphrase
is wrong in F<RT_SiteConfig.pm>. Note that you can use either GPG Agent or
set the passphrase in the site config, you need not do both.

=head2 Service Level Agreements (SLAs)

RTIR used to have a simple Service Level Agreements (SLA) implementation.
L<RT::Extension::SLA> was prototyped on it, but vastly improved. In RTIR 3.0
we removed the SLA implementation in the core of RTIR that was in conflict
with the extension.

RT 4.4 has cored L<RT::Extension::SLA>, please disable SLA on the Incidents
queues.  You will encounter a race condition between the core SLA and the RTIR
scrips that synchronize due dates between an incident and its most due active
child.  If you need to manage incident due dates using the core SLA, you can
disable the RTIR scrips that manage due dates on the Incidents queues.

=cut
