=head1 Upgrading to 3.2

The following describes some of the key components of the upgrade
to RTIR 3.2 from previous versions of RTIR, specifically
from RTIR 3.0. The other UPGRADING documents contain details
for previous versions.

=head2 F<add_constituency> Moved

The F<add_constituency> script has been moved from F<etc> to the standard
F<bin> directory.
