=head1 Upgrading to 3.2

The following describes some of the key components of the upgrade
to RTIR 3.2 from previous versions of RTIR, specifically
from RTIR 3.0. The other UPGRADING documents contain details
for previous versions.

=head2 F<add_constituency> Moved

The F<add_constituency> script has been moved from F<etc> to the standard
F<bin> directory.

=head2 Chart URLs changed

RT 4.2 added improved charting (multiple group bys, calculations, etc),
but the arguments passed have changed. If you have bookmarks pointing to
/RTIR/Search/Reporting.html they likely will not work on RTIR 3.2.

