=head1 Upgrading to 3.4

The following describes some of the key components of the upgrade
to RTIR 3.4 from RTIR 3.2.  The other UPGRADING documents contain
details for previous versions.

=head2 Constituency support

=head3 Setting constituency based on email headers

RTIR 3.2 allowed sites to set ticket constituencies based on
the C<X-RT-Mail-Extension> message header. As RTIR now supports
the features of 'regular' RT queues for constituencies, using
message headers to set RTIR constituencies is no longer available.


